name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: src/recipe-app # Explicitly set working directory (package.json not in root)
        run: npm install  # Installs dependencies from the package.json in specified directory

      # Step 4: Run tests placeholder
      - name: Run tests
        working-directory: src/recipe-app # Explicitly set working directory
        run: npm test #run test
