name: CI/ CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write # Required for `actions/deploy-pages`


    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: src/recipe-app # Explicitly set working directory (package.json not in root)
        run: npm install  # Installs dependencies from the package.json in specified directory

      # Step 4: Run tests
      - name: Run tests
        working-directory: src/recipe-app # Explicitly set working directory
        run: npm test #run test

       # Step 5: Build the app
      - name: Build the app
        working-directory: src/recipe-app
        run: npm run build

      # Step 6: Deploy to `gh-pages`
      - name: Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin
          git switch gh-pages || git switch -C gh-pages
          git rm -rf . # Remove old files
          cp -r src/recipe-app/dist/* . # Copy built files to root
          git add .
          git commit -m "Deploy updated files to gh-pages"
          git push origin gh-pages --force
